version: '3.7'

services:
    python_build:
        build:
            dockerfile: ./dev/Dockerfile
            context: ./
        image: onepycoder/python:3.8.0.2

    python_build_cms:
        build:
            dockerfile: ./dev/cms.Dockerfile
            context: ./
        image: onepycoder/landing_cms:1.05
