# Generated by Django 2.1.8 on 2019-04-18 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='block',
            options={'ordering': ['position']},
        ),
    ]
