# Generated by Django 2.1.8 on 2019-04-18 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20190418_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='in_menu',
            field=models.BooleanField(default=False),
        ),
    ]
