# Generated by Django 2.1.8 on 2019-04-18 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_block_in_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='content',
            field=models.TextField(default='', max_length=2048),
        ),
    ]
