# Generated by Django 2.2 on 2019-04-19 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_team'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Team',
            new_name='TeamMember',
        ),
    ]
