# Generated by Django 2.2.5 on 2019-10-04 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20190419_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='menu_name',
            field=models.CharField(default='default', max_length=32),
            preserve_default=False,
        ),
    ]
